# Generated by Django 2.2 on 2020-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('national_id', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField(default=0)),
                ('ward', models.CharField(max_length=30)),
            ],
        ),
    ]
