# Generated by Django 2.2 on 2020-05-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacific', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
    ]
